### ISSUE TITLE
Long Polling

### ISSUE THREAD

**Issue by themester** [secu77/Telegram-Bots#1]
```El método de Long Polling se caracteriza porque el programa (bot) manda peticiones a una URL preguntando por nuevas actualizaciones```
Hasta ahi es correcto. La imagen que le acompaña es incorrecta. Asi que supongo que la definicion tambien.

El metodo Long Polling no hace peticiones todo el rato. Hace una peticion y espera a recibir los datos. Si hay datos disponibles el cliente recibe estos. Si no, espera. La conexion se queda abierta hasta que recibe datos.

Sacado del articulo de Wikipedia enlazado [aqui](https://core.telegram.org/bots/api#getupdates).

```If the server has no new information for the client when the poll is received, instead of sending an empty response, the server holds the request open and waits for response information to become available. Once it does have new information, the server immediately sends an HTTP/S response to the client, completing the open HTTP/S Request. Upon receipt of the server response, the client often immediately issues another server request.```

**Comment by secu77** [comment]
Explicación del Método Long Polling actualizada y corregida.
